# ingress.yaml â€” routes host to app service
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pydbapi-ingress
  namespace: pydbapi
  labels:
    app: pydbapi
    environment: dev
spec:
  ingressClassName: nginx
  rules:
    # Dev host for kind. Add to /etc/hosts: 127.0.0.1 pydbapi.local
    - host: "pydbapi.local"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: pydbapi
                port:
                  number: 80
  # tls:
  #   - hosts: ["pydbapi.local"]
  #     secretName: pydbapi-tls
