# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: pydbapi-app-secrets
  namespace: pydbapi
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "admin"
  POSTGRES_DB: "pydbapi_db"
  SECRET_KEY: "IuHWBMF2o38tJxecd1voYb54xUIWaSmVf8g4xyanhAE"
  FIRST_SUPERUSER: "admin@example.com"
  FIRST_SUPERUSER_PASSWORD: "superuser-password"
