# service.yaml â€” ClusterIP for the app
apiVersion: v1
kind: Service
metadata:
  name: pydbapi
  namespace: pydbapi
  labels:
    app: pydbapi
    environment: dev
spec:
  selector:
    app: pydbapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
