global:
  postgresql:
    auth:
      postgresPassword: admin
  security:
    allowInsecureImages: "True"
primary:
  persistence:
    size: 50Gi
  # resources:
  #   requests:
  #     cpu: 2
  #     memory: 512Mi
  #   limits:
  #     cpu: 3
  #     memory: 1024Mi
image:
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: 17.6.0
